### PR TITLE
Adding index.js to fix NPM entry point

### PR DESCRIPTION
**Pull request by yogeshmangaj**

### CODE REVIEW

**Comment by rubenv** [comment]
Wouldn't it be better to just point to the right filename?

**Comment by yogeshmangaj** [comment]
@rubenv Adding `index.js` this way, also allows one to import the module as a relative location, e.g.: `require('./node_modules/angular-select2');`

**Comment by rubenv** [comment]
I don't think that's a good idea. Why would you ever want to do that?

**Comment by yogeshmangaj** [comment]
@rubenv Good question!
I'm not entirely sure why would I do that except if I ever need to keep the module somewhere other than the `node_modules` directory, but again no good reason why that would be required.
Just thinking aloud, if we change the contents of `index.js` to this:

    require("./dist/angular-select2");
    module.exports = "angular-select2"

it will allow you to add an inline require statement like this:

    angular.module("myApp", [require("angular-select2")])

**Comment by rubenv** [comment]
> require("./dist/angular-select2");
> module.exports = "angular-select2"

That doesn't look like it'll work.

I went ahead and used your original suggestion from your e-mail. That should do the trick.

Release is up on NPM.

**Pull request closed without merging**
